### ISSUE TITLE
[Bug report] Bug in make confsource: Unable to set the LBUFF to 64k

### ISSUE THREAD

**Issue by mdziczkowski** [RhostMUSH/trunk#84] opened 2021-04-17 08:53 UTC
While attempting to set LBUFF to 64k, I get the message about `ulimit`, even if it results:

- `ulimit` : unlimited
- `ulimit -s` : above the one given in the message

**Comment by Chalice** [comment] 2021-04-17 11:11
Hi,

What is the exact message you are getting?

**Comment by mdziczkowski** [comment] 2021-04-17 11:28
> You must have stack size set to 16384 or higher to use 64K lbufs.
> Yours is currently set to 8192.  ulimit -s 16500 to set

Even if when I type in the system terminal `ulimiit -s` it shows me a different and bigger value then given above

**Comment by mrsenile** [comment] 2021-04-17 14:26
Can you show us the output of 'ulimit -a' please?

**Comment by mdziczkowski** [comment] 2021-04-17 15:00
> core file size          (blocks, -c) unlimited
> data seg size           (kbytes, -d) unlimited
> scheduling priority             (-e) 0
> file size               (blocks, -f) unlimited
> pending signals                 (-i) 3
> max locked memory       (kbytes, -l) 4096
> max memory size         (kbytes, -m) unlimited
> open files                      (-n) 4096
> pipe size            (512 bytes, -p) 8
> POSIX message queues     (bytes, -q) unlimited
> real-time priority              (-r) 0
> stack size              (kbytes, -s) unlimited
> cpu time               (seconds, -t) unlimited
> max user processes              (-u) unlimited
> virtual memory          (kbytes, -v) unlimited
> file locks                      (-x) unlimited

**Comment by mrsenile** [comment] 2021-04-17 15:01
AHHH, that's why.  I likely didn't put in proper logic for 'unlimited' for stack size, it expect an actual value there and not 'unlimited'.

Try setting it to like 32768 and it should work fine.  

Good catch on that and we'll look to fix that in the future.

**Comment by mdziczkowski** [comment] 2021-04-17 15:09
I had earlier a value of 65535 in the stack (-s) part and it gave me the same message, with is strange

**Comment by mdziczkowski** [comment] 2021-04-17 15:11
> Good catch on that and we'll look to fix that in the future.

you could add in the code to check if it's either numeric or "unlimited" and if numeric then check it's value. It shuuld solve it

**Comment by mrsenile** [comment] 2021-04-17 15:12
I can't reproduce it with a value, but let me add some error handling in it just in case.  I should have an update pushed in 5-10  minutes.

**Comment by mrsenile** [comment] 2021-04-17 15:18
Ok, this should be fixed in the latest pull.  Effected files are asksource.sh and asksource.blank in the ~/bin directory.

**Closed by mrsenile** 2021-04-17 15:18 UTC
